### PR TITLE
Enhancements for contact fields, retrieve/update/create, batches and group create

### PR DESCRIPTION
**Pull request by draffensperger**
Hi @aliang, in the past couple months I've done a fair number of changes to the gem as I needed functionality for our Google contacts sync feature. I also tried to merge in your changes since my last pull request. I've documented the main changes in the updated README.markdown.

I figured it would be great to suggest these features be added back into the base gem to allow others to more easily use them.

### CODE REVIEW

**Comment by draffensperger** [comment]
I was contacted recently by someone interested in the batch processing part of this gem (my fork has one star). I've also made a few smaller fixes recently. Do you think you'd have time to review and merge this in or should do you think it would be better for me to push the gem under a new name?

**Comment by AllThatIsTheCase** [comment]
I realize it's a whole lot of code to review, but I'd *love* to see this merged. I would offer that since the Travis tests pass, it'd be a low-risk merge, and I really, really need this. I've checked out the gem via git in the interim, but I'd rather use the official gem.

**Comment by aliang** [comment]
I actually started reviewing this a while back, but it would be helpful if the pull request was broken down by feature so it wouldn't be a giant release.

**Comment by draffensperger** [comment]
OK, I can try to do that in the next week or two.

**Comment by draffensperger** [comment]
I'm closing this and will add the first broken out PR (too me longer than I had hoped to get to this).

**Pull request closed without merging**
