### PR TITLE
Improve specs

### PR DESCRIPTION
**Pull request by Jeiwan**
1. Added `.rspec` file with default configuration.
2. Moved helper methods like `contact_set_json`, `group_set_json` etc. to a separate file, located in `spec/support` folder.
3. Moved data-files (jsons) to `spec/fixtures` folder.
4. Split the huge `google_contacts_api_spec.rb` into separate files for better readability.
5. Improved specs syntax for it to fit `describe-context-it-expect` model.
6. Added some minor specs, like `ResultSet` and `Result`.
7. Slightly improved `GroupSet`, added a check for empty feed.

The logic of the specs wasn't changed, only refactoring and rearrangement of files were done.

### CODE REVIEW

**Comment by aliang** [comment]
At first glance, looks really useful. Will review more fully soon (this isn't my day job sadly!)

**Comment by aliang** [comment]
It would be nice if at least some of this was in separate commits rather than a mega-commit. At the very least, the additional check in `GroupSet` (7) should be in its own commit. I'd also say the additional minor specs (6) and the changes in spec syntax (5) should each have their own commits as well.

**Comment by Jeiwan** [comment]
Ok, will do this today.

**Comment by Jeiwan** [comment]
@aliang Done!

**Comment by aliang** [comment]
Looks good!

**Pull request merged**
